#!/bin/bash

THIS=$(dirname $(readlink -f $0))

. ./install
. ./cleanup
. ./copy

# now run build script
SKIPINITRFS=true
cd ../../
. ./build

# setup initrd now, to include aufs
apt-get update
apt-get install aufs-dkms

cd initramfs
. ./initramfs_create

mv -f $INITRAMFS.img $LIVEKITDATA/$LIVEKITNAME/boot/initrfs.img
cp -vf $THIS/bootfiles/* $LIVEKITDATA/$LIVEKITNAME/boot/
