#!/bin/bash

. ./install
. ./cleanup
. ./copy

# now run build script
SKIPINITRFS=true
cd ../../
. ./build

# re-setup initrd to include aufs
apt-get update
apt-get install aufs-dkms

cd initramfs
. ./initramfs_create

cp -f $INITRAMFS.img $LIVEKITDATA/$LIVEKITNAME/boot/initrfs.img
