#!/bin/bash

CWD=$(pwd)

. ./install
. ./cleanup
. ./copy

# now run build script
SKIPINITRFS=true
cd ../../
. ./build

# setup initrd now, to include aufs
apt-get update
apt-get install aufs-dkms

cd initramfs
. ./initramfs_create

mv -f $INITRAMFS.img $LIVEKITDATA/$LIVEKITNAME/boot/initrfs.img
cp -f $CWD/bootfiles/* $LIVEKITDATA/$LIVEKITNAME/boot/
