#!/bin/bash

apt-get dist-upgrade
# if kernel was upgraded, you may need to reboot
apt-get install mc squashfs-tools genisoimage zip psmisc net-tools
apt-get remove libicu* libperl* libxml2 mime-support perl perl-modules-5.24 sgml-base shared-mime-info xdg-user-dirs xml-core
