#!/bin/bash

cat ~/.gtk-bookmarks | fgrep -v ///media/ | fgrep -v "file:/// /" | egrep -v '^$' > ~/.gtk-bookmarks.tmp 2>/dev/null
ls -1 /media | while read LINE; do
   echo "file:///media/$LINE $LINE" >> ~/.gtk-bookmarks.tmp
done

echo "file:/// /" >> ~/.gtk-bookmarks.tmp # add root at the end

mv -f ~/.gtk-bookmarks.tmp ~/.gtk-bookmarks
