#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/root/.Xmodmap"

# merge xresource settings
xrdb -merge ~/.Xresources

# set background color and big wait mouse cursor
xsetroot -solid '#111111'
xsetroot -xcf /usr/share/icons/breeze_cursors/cursors/watch 37

# preload compton and fluxbox to cache
(compton --help; fluxbox --help) >/dev/null 2>/dev/null

# preload wallpaper
cat /usr/share/wallpapers/slax_wallpaper.jpg > /dev/null 2>/dev/null

# Keep black screen for first two seconds while the sound plays.
# This slows startup by 2 seconds, but it is nice effect.
SND=/usr/share/sounds/startup.wav
if [ -r $SND ]; then
   cat $SND > /dev/null # preload
   aplay $SND &
   sleep 1 &
   SOUNDPID=$!
fi

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
#
# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# We need to postpone compton after fluxbox starts, else it won't set
# the transparency of toolbar properly... So we check the fehbg file,
# which is created by fluxbox at the phase when it sets background.
# Once the file exist, fluxbox-toolbar is already started

SIGNALFILE=~/.fehbg
rm -f $SIGNALFILE
(
   while [ ! -e $SIGNALFILE ]; do
      sleep 0.1
   done
   compton --sw-opti -e 0.9 --fade-exclude 'role*="fluxbox-toolbar"' --opacity-rule '70:role*="fluxbox-toolbar"' --no-fading-destroyed-argb -D 5 -c -f -l -2 -t -2 -r 0 -o 1 -z --shadow-exclude 'bounding_shaped' &
) &

# We want to run systrayicon only after the volumeicon is started
# So we have to wait until it is visible to xwinfo
(
   # volume icon in system tray. Can fail if no soundcard is detected
   volumeicon &
   while ! xwininfo -name volumeicon >/dev/null 2>&1 && pgrep volumeicon >/dev/null 2>&1; do
      sleep 0.1
   done
   # volume icon has launched, give it some time to init
   sleep 1
   # system shutdown/logout icon in system tray
   systrayicon --command fblogout --iconfile /usr/share/icons/locolor/16x16/actions/system-shutdown-symbolic.png &
) &

# In all cases, wait for the sound sleeper.
# If startup took longer (sound completed already), no extra wait
wait $SOUNDPID

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
