#!/bin/sh

# imlib2-config script seems to be no longer present in Debian installation, but fluxbox
# compilation requires it. This is minimum variant which will make fluxbox compile with imlib2
# support so we can have nice min/max/close icons in window titlebar

while test $# -gt 0; do
  case $1 in
    --version)
      echo 1.10.0
      ;;
    --cflags)
      ;;
    --libs)
      echo -lImlib2
      ;;
  esac
  shift
done

exit 0
