#!/bin/bash

CWD=$(dirname $(readlink -f $0))

NAME=fluxbox
VERSION=1.3.5

# first install stock version

apt-get update
apt-get install --no-install-recommends --yes $NAME feh compton volumeicon-alsa murrine-themes leafpad qalculate-gtk
. ../../cleanup

(cd rootcopy && cp --parents -afr * /)
chown -R guest.users /home/guest

savechanges /$NAME-stock.sb

cd /
unsquashfs /$NAME-stock.sb

# then, we want to patch it to implement window resizing!
# so we will recompile whole package

REBUILD=/tmp/$NAME-rebuild-$$

apt-get update
apt-get --yes build-dep $NAME

mkdir -p $REBUILD
cd $REBUILD

apt-get source $NAME

cd $NAME-$VERSION

cat $CWD/patches/fluxbox-slax.diff > debian/patches/fluxbox-slax.diff
echo fluxbox-slax.diff >> debian/patches/series

dpkg-buildpackage -us -uc

rm -Rf debian/$NAME/DEBIAN
rm -Rf debian/$NAME/usr/share/doc
rm -Rf debian/$NAME/usr/share/images

cp debian/$NAME/usr/bin/fluxbox /squashfs-root/usr/bin


# add xlunch from sources
wget -O /tmp/xlunch.tar.gz https://github.com/Tomas-M/xlunch/archive/master.tar.gz
cd /tmp
tar -xf xlunch.tar.gz
cd xlunch-master
make
cp xlunch /squashfs-root/usr/bin
mkdir -p /squashfs-root/usr/share/icons/hicolor/48x48/apps/
cp extra/ghost.png /squashfs-root/usr/share/icons/hicolor/48x48/apps/xlunch_ghost.png

# add tray icon launcher
wget -O /tmp/systrayiconlauncher.tar.gz https://github.com/Tomas-M/SystrayIconLauncher/archive/master.tar.gz
cd /tmp
tar -xf systrayiconlauncher.tar.gz
cd SystrayIconLauncher-master
apt-get install --yes libgtk2.0-dev
make
cp systrayicon /squashfs-root/usr/bin

dir2sb /squashfs-root /03-desktop.sb
