#!/bin/bash

CWD=$(dirname $(readlink -f $0))

NAME=fluxbox
VERSION=1.3.5

# first install stock version

apt-get update
apt-get install --no-install-recommends --yes $NAME feh compton
. ../../cleanup

(cd rootcopy && cp --parents -afr * /)
savechanges /$NAME-stock.sb

cd /
unsquashfs /$NAME-stock.sb

# then, we want to patch it to implement window resizing!
# so we will recompile whole package

REBUILD=/tmp/$NAME-rebuild-$$

apt-get update
apt-get --yes build-dep $NAME

mkdir -p $REBUILD
cd $REBUILD

apt-get source $NAME

cd $NAME-$VERSION

cat $CWD/patches/fluxbox-slax.diff > debian/patches/fluxbox-slax.diff
echo fluxbox-slax.diff >> debian/patches/series

dpkg-buildpackage -us -uc

rm -Rf debian/$NAME/DEBIAN
rm -Rf debian/$NAME/usr/share/doc
rm -Rf debian/$NAME/usr/share/images

cp debian/$NAME/usr/bin/fluxbox /squashfs-root/usr/bin


# add xlunch from sources
wget -O /tmp/xlunch.tar.gz --no-check-certificate https://github.com/Tomas-M/xlunch/archive/master.tar.gz
cd /tmp
tar -xf xlunch.tar.gz
cd xlunch-master
make
cp xlunch /squashfs-root/usr/bin

savechanges /03-desktop.sb /squashfs-root
