#!/bin/bash

if [ "$1" = "--help" -o "$1" = "" -o "$2" = "" ]; then
   echo "$0 - make slax squashfs bundle (module)"
   echo "usage: $0 [source_directory] [destination_file] [(optional)-keep-as-directory] [(optional)other_mksquashfs_arguments]"
   echo "note: destination file will be erased"
   exit
fi

mksquashfs "$1" "$2" -comp xz -b 1024k -Xbcj x86 -noappend $3 $4 $5 $6 $7 $8 $9
