#!/bin/bash

CWD=$(dirname $(readlink -f $0))

NAME=fluxbox
VERSION=1.3.5

mkdir -p /squashfs-root
#mount -t tmpfs tmpfs /squashfs-root

# we want to patch fluxbox to implement window resizing!
# so we will recompile whole package

REBUILD=/tmp/$NAME-rebuild-$$

apt update
apt --yes build-dep $NAME

mkdir -p $REBUILD
cd $REBUILD

apt source $NAME

cd $NAME-$VERSION

cat $CWD/patches/fluxbox-slax.diff > debian/patches/fluxbox-slax.diff
echo fluxbox-slax.diff >> debian/patches/series

dpkg-buildpackage -us -uc

rm -Rf debian/$NAME/DEBIAN
rm -Rf debian/$NAME/usr/share/doc
rm -Rf debian/$NAME/usr/share/images

cp debian/$NAME/usr/bin/fluxbox /squashfs-root/usr/bin


# add xlunch from sources
wget -O /tmp/xlunch.tar.gz https://github.com/Tomas-M/xlunch/archive/v4.7.4.tar.gz
cd /tmp
tar -xf xlunch.tar.gz
cd xlunch-4.7.4
make
cp xlunch /squashfs-root/usr/bin
cp extra/gentriesquick /squashfs-root/usr/bin/xlunch_genquick
mkdir -p /squashfs-root/usr/share/icons/hicolor/48x48/apps/
cp extra/ghost.png /squashfs-root/usr/share/icons/hicolor/48x48/apps/xlunch_ghost.png

# add tray icon launcher
wget -O /tmp/systrayiconlauncher.tar.gz https://github.com/Tomas-M/SystrayIconLauncher/archive/master.tar.gz
cd /tmp
tar -xf systrayiconlauncher.tar.gz
cd SystrayIconLauncher-master
apt install --yes libgtk2.0-dev
make
cp systrayicon /squashfs-root/usr/bin


# add gtkdialog
wget -O /tmp/gtkdialog.tar.gz https://github.com/Tomas-M/GTKdialog/archive/master.tar.gz
cd /tmp
tar -xf gtkdialog.tar.gz
cd GTKdialog-master
make
cp gtkdialog /squashfs-root/usr/bin


# battery icon app
cd /tmp
wget https://github.com/valr/cbatticon/archive/1.6.10.tar.gz
tar -xf 1.6.10.tar.gz
cd cbatticon-1.6.10
cp -R /usr/include/glib-2.0/* /usr/include
cp -R /usr/include/gtk-2.0/* /usr/include
apt install --yes libnotify-dev
sed -i "s/WITH_GTK3 = 1/WITH_GTK3 = 0/" Makefile
CFLAGS="-O2 \
-I/usr/lib/x86_64-linux-gnu/glib-2.0/include/ \
-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include/ \
-I/usr/include/gdk-pixbuf-2.0/ \
-I/usr/include/atk-1.0/ \
-I/usr/include/cairo \
-I/usr/include/pango-1.0 \
-I/usr/include/glib-2.0 \
-I/usr/include/gtk-2.0" \
make
cp cbatticon /squashfs-root/usr/bin
