#!/bin/bash

# installpkg squashfs-tools cdrtools lzo lz4

CHANGES=/tmp/slax-build
UNION=$CHANGES/union
THIS=$(dirname $(readlink -f $0))

modprobe aufs || exit 1

mkdir -p $CHANGES/empty
mkdir -p $UNION
mount -t aufs -o xino="/tmp/.xino",trunc_xino,br="$CHANGES/empty" aufs "$UNION"

for i in $(ls -1 modules); do
   echo $i
   mkdir -p $CHANGES/$i
   mount -o remount,add:0:"$CHANGES/$i" aufs "$UNION"
   touch $UNION/$i
   cat modules/$i/packages | egrep -v '^$' | while read PKG; do
      installpkg -root $UNION /media/cdrom/slackware*/*/$PKG*.txz
   done
   mount -o remount,mod:"$CHANGES/$i=ro" aufs "$UNION"
done

umount $UNION

rm -f /vmlinuz
cat /boot/vmlinuz-slax* > /vmlinuz

sed -i -r 's/^LIVEKITNAME.*/LIVEKITNAME="slax"/' $THIS/../../config
sed -i -r 's/^NETWORK.*/NETWORK=true/' $THIS/../../config

SKIPINITRFS=true
SKIPCOREMOD=true
cd ../../
. ./build

cd initramfs
. ./initramfs_create

echo $INITRAMFS
mv -f $INITRAMFS.img $LIVEKITDATA/$LIVEKITNAME/boot/initrfs.img
cp -vfR $THIS/bootfiles/* $LIVEKITDATA/$LIVEKITNAME/boot/

rm -f /vmlinuz
