#!/bin/bash

# first install stock version

apt update
apt install --no-install-recommends --yes \
    fluxbox \
    feh \
    compton \
    volumeicon-alsa \
    murrine-themes \
    libnotify4 \
    libgtk2.0-0 \
    scrot

/cleanup

(cd rootcopy && cp --parents -afr * /)

# create user directories
for dir in Desktop Documents Downloads Music Pictures Public Templates Videos; do
   mkdir -p /home/guest/$dir
   mkdir -p /root/$dir
done

chown -R guest.users /home/guest
chown -R guest.users /home/guest/.gtkrc-2.0
chown -R guest.users /home/guest/.config
