#!/bin/bash

CWD=$(dirname $(readlink -f $0))

apt update
apt install --no-install-recommends --yes \
    galculator \
    pcmanfm \
    lxtask \
    connman-gtk at-spi2-core \
    scite \
    xarchiver xdg-utils libgconf-2-4

/cleanup

(cd rootcopy && cp --parents -afr * /)

rm -Rf /root/.fluxbox
rm -f /root/.gtk-bookmarks
rm -f /usr/share/applications/lxtask.desktop
rm -f /usr/share/applications/galculator.desktop
rm -f /usr/share/applications/pcmanfm.desktop
rm -f /usr/share/icons/hicolor/scalable/apps/*

