#!/bin/bash
DIR="/tmp/slax-data-511/slax/boot"
FILE="initrfs.img"

if [ ! -d "$DIR/$FILE" ]; then
   echo "Directory does not exist $DIR/$FILE"
   exit
fi

cd "$DIR/$FILE"
find . -print | cpio -o -H newc 2>/dev/null | xz -T0 -f --extreme --check=crc32 >"$DIR/$FILE".x

cd "$DIR"
umount "$DIR/$FILE"
rmdir "$DIR/$FILE"
mv "$DIR/$FILE".x "$DIR/$FILE"
