#!/bin/bash

CWD=$(dirname $(readlink -f $0))

apt-get update
apt-get install --no-install-recommends --yes \
    gnome-calculator \
    tuxcmd \
    lxtask \
    xarchiver xdg-utils libgconf-2-4

. ../../cleanup

(cd rootcopy && cp --parents -afr * /)

savechanges /apps-stock.sb
cd /
unsquashfs -no-xattrs /apps-stock.sb
rm -Rf /squashfs-root/root/.fluxbox
rm -f /squashfs-root/root/.gtk-bookmarks

rm -f /squashfs-root/usr/share/applications/lxtask.desktop
rm -f /squashfs-root/usr/share/applications/tuxcmd.desktop
rm -f /squashfs-root/usr/share/applications/org.gnome.calculator.desktop

dir2sb /squashfs-root /04-apps.sb
