#!/bin/bash

# first install stock version
apt-get install --no-install-recommends --yes fluxbox
. ../cleanup
savechanges /fluxbox-stock.sb

# then, we want to patch it to implement window resizing!
# so we will recompile whole package

NAME=fluxbox
VERSION=1.3.5

REBUILD=/tmp/$NAME-rebuild-$$
CWD=$(dirname $(readlink -f $0))

apt-get update
apt-get build-dep $NAME

mkdir -p $REBUILD
cd $REBUILD

apt-get source $NAME

cd $NAME-$VERSION

cat $CWD/patches/fluxbox-slax.diff > debian/patches/fluxbox-slax.diff
echo fluxbox-slax.diff >> debian/patches/series

dpkg-buildpackage -us -uc

rm -Rf debian/$NAME/DEBIAN
rm -Rf debian/$NAME/usr/share/doc
rm -Rf debian/$NAME/usr/share/images

. ../cleanup
savechanges /fluxbox-mods.sb debian/$NAME

# combine them together, todo
