#!/bin/bash

THIS=$(dirname $(readlink -f $0))

sed -i -r 's/^LIVEKITNAME.*/LIVEKITNAME="slax"/' $THIS/../../config
sed -i -r 's/^NETWORK.*/NETWORK=true/' $THIS/../../config

. ./copy
. ./install
. ./cleanup
. ./copy

# now run build script
SKIPINITRFS=true
cd ../../
. ./build

# setup initrd now, to include aufs
apt-get update
apt-get install aufs-dkms linux-headers-$(uname -r) --yes

cd initramfs
. ./initramfs_create

# unpack the sb archive and add aufs modules to /lib/modules
cd $LIVEKITDATA/$LIVEKITNAME
unsquashfs 01-core.$BEXT
cp -a /$LMK/kernel/fs/aufs squashfs-root/$LMK/kernel/fs
rm -f 01-core.$BEXT
mksquashfs squashfs-root 01-core.$BEXT -comp xz -b 1024K -always-use-fragments || exit
rm -Rf squashfs-root

mv -f $INITRAMFS.img $LIVEKITDATA/$LIVEKITNAME/boot/initrfs.img
cp -vf $THIS/bootfiles/* $LIVEKITDATA/$LIVEKITNAME/boot/
